### ISSUE TITLE
outputting solution as raster

### ISSUE THREAD

**Issue by colobrien** [prioritizr/prioritizr#198] opened 2021-05-28 23:23 UTC
I'm running prioritizr with Gurobi optimizer on an HPC system using a slurm (batch) job, with huge input rasters.  The job takes about 2 days and finishes, saying it reached a solution (via the log files it outputs).  However, I can't see or output the solution raster.  This is the code I've tried:

optR <- raster(s1)
writeRaster(optR, filename = "optimized-400m.tif")

Where s1 is the solution.  What am I doing wrong?

Thank you!

**Comment by jeffreyhanson** [comment] 2021-05-29 00:00
Thanks for reaching out!

Just to clarify is the `writeRaster()` R code part of the batch job? If so, I wonder if you need code in the batch job file to save the rasters to a persistent location? E.g. I previously used a HPC system several years ago (IIRC using PBS), and if I just saved a file to the current working directory in a batch job file, then the file would be automatically deleted when the job finished. To ensure that I could access the files after the jobs completed, I needed to include additional commands in the job file to copy the files to a persistent storage location (e.g. my user directory on the university system). Is this relevant in your case? 

To test this, you could create a dummy batch job that just saves the simulated rasters data to disk? This way the batch jobs will complete very quickly. E.g. use some R code like this:

```
library(prioritizr)
data(sim_pu_raster)
writeRaster(sim_pu_raster, filename = "test-run-1.tif", NAflag = -9999)
```

If those rasters don't appear after your jobs have finished, then you know it's something going on with the HPC system and not prioritizr. If that happens, then you could work out what extra commands are needed in the job file to save it to a persistent storage location?

Does that help? Please let me know if I've missed something or if anything's not clear?

**Comment by jeffreyhanson** [comment] 2021-05-29 00:01
Sorry, I accidently closed the issue by accidently clicking the wrong button.

**Comment by colobrien** [comment] 2021-05-29 00:57
Yes, writeRaster is in the R batch job.  That is a good idea... I will try maybe adding a path to the raster name? If that doesn't work look for other ways to save it to persistent storage.  Thanks!

**Comment by jeffreyhanson** [comment] 2021-05-29 01:06
Ah ok. Yeah, specifying a path in the raster name could be one way to do this. No worries! I'll close this issue now since it seems like we've identified that the issue is with the batch job, but please feel free to re-open if it if it later turns out to be an issue with prioritizr.

**Closed by jeffreyhanson** 2021-05-29 01:06 UTC
Labels: question

**Comment by colobrien** [comment] 2021-06-16 22:39
I am reopening this thread because after trying some things, I think the issue is with prioritizr/Gurobi.  I did finally get an output raster from the prioritizer routine, but it is empty.  I downloaded the log files from the procedure (attached) and although it says it found a solution... it says the cell values are all NA.  Can you tell why this is happening?

Thank you!

[rLog500_prob.txt](https://github.com/prioritizr/prioritizr/files/6666189/rLog500_prob.txt)
[rLog500_solv.txt](https://github.com/prioritizr/prioritizr/files/6666191/rLog500_solv.txt)
