### ISSUE TITLE
add_max_features_objective doesn't recognise feature targets

### ISSUE THREAD

**Issue by lizlaw** [prioritizr/prioritizr#103] opened 2018-12-12 02:17 UTC
Hi gang, 

Just playing around with different objective functions, and am having issues with the max_features_objective in that it doesn't seem to recognise the targets correctly. I've tried inputting targets as add_relative_targets(matrix) and as add_manual_targets(tibble). 

Looking in the compile(problem) output it seems that the feature targets have just not transferred across to the rhs. 

I'm using a multi-zone problem, but it also seems to manifest in the single zone problem in the documentation (for which the solution is all 0)...

Cheers,
Liz

**Comment by jeffreyhanson** [comment] 2018-12-12 02:21
This sounds pretty serious - could you please provide a reproducible example?

**Comment by lizlaw** [comment] 2018-12-12 02:30
Yeah, sorry to be the bearer of this.

Reproducible example (simply the one on the https://prioritizr.net/reference/add_max_features_objective.html). Session info below. I thought it might be just my development version, but did note that it was on the reference page as well.

```{r}
library(prioritizr)
library(gurobi)

# load data
data(sim_pu_raster, sim_pu_zones_stack, sim_features, sim_features_zones)

# create problem with maximum features objective
p1 <- problem(sim_pu_raster, sim_features) %>%
  add_max_features_objective(1500) %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions()
# solve problem
s1 <- solve(p1)

# plot solution
plot(s1, main = "solution", axes = FALSE, box = FALSE)

# feature representation
feature_representation(p1, s1)

```

sessionInfo()

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] prioritizr_4.0.2.7 proto_1.0.0        raster_2.8-4       sp_1.3-1          

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19     gurobi_8.0-1     lattice_0.20-35  codetools_0.2-15 fansi_0.2.3     
 [6] utf8_1.1.4       crayon_1.3.4     assertthat_0.2.0 slam_0.1-43      grid_3.5.1      
[11] magrittr_1.5     pillar_1.3.0     cli_1.0.0        rlang_0.2.2      uuid_0.1-2      
[16] rstudioapi_0.7   Matrix_1.2-14    tools_3.5.1      parallel_3.5.1   yaml_2.2.0      
[21] compiler_3.5.1   tibble_1.4.2

**Comment by jeffreyhanson** [comment] 2018-12-12 02:56
Ok, I just tried that example and it looks like the problem with that example specifically---so this might not be illustrative of the problem that you're encountering---is that the budget is too low to meet any of the targets for that species.

If we increase the budget to 20k (total cost of study area is approx 18k), then we get a solution that meets all of the targets.

```
# load packages
library(prioritizr)
library(gurobi)

# load data
data(sim_pu_raster, sim_pu_zones_stack, sim_features, sim_features_zones)

# create problem with maximum features objective
p1 <- problem(sim_pu_raster, sim_features) %>%
  add_max_features_objective(20000) %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions() %>%
  add_default_solver(gap = 0)

# solve problem
s1 <- solve(p1)

# calculate representation - all targets met
feature_representation(p1, s1)

# calculate cost of solution, this is 1978
cellStats(s1 * sim_pu_raster, "sum")
```

We can also double check that 1500 is to small to meet any targets, by calculating the cost of the cheapest solution needed to meet their target.

```
# calculate costs
costs <- sapply(seq_len(nlayers(sim_features)), function(i) {
 s <- problem(sim_pu_raster, sim_features[[i]]) %>%
      add_min_set_objective() %>%
      add_relative_targets(0.1) %>%
      add_binary_decisions() %>%
      add_default_solver(gap = 0)
      solve()
  cellStats(s * sim_pu_raster, "sum")
})

# print costs, min value is 1644.134
costs 
```

So, let's try resolving the problem with a budget of 1800

```
# create problem with maximum features objective
p2 <- problem(sim_pu_raster, sim_features) %>%
  add_max_features_objective(1800) %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions() %>%
   add_default_solver(gap = 0)

# solve problem
s2 <- solve(p2)

# calculate representation - here we meet the 10% targets for 2 species
feature_representation(p2, s2)

# calculate cost, this is 1685
cellStats(s2 * sim_pu_raster, "sum")
```

Is it possible that the targets you're using are too high given the budget?

**Comment by lizlaw** [comment] 2018-12-12 03:00
I don’t think so but will double-check… will have to be tomorrow though as I am currently running a different version, plus it’s late and I need food.

**Comment by jeffreyhanson** [comment] 2018-12-12 03:14
Ok - no worries - thanks for raising this!

**Comment by lizlaw** [comment] 2018-12-12 14:33
OK totally my bad I think - I wanted it to be something it was not, apparently - very sorry I really should have waited until I had food and revisited this in the morning. 

But that does lead me to suggest that this problem is very much on the thorny end of triage. Maybe a feature suggestion here would be to have two types of feature targets, one that gets fed into the maximisation objective, and one that gets fed into the constraints. I think I was a little confused that by “add_representation_targets” to this objective is not the same thing as for the minimum set problems. 

Cheers,
Liz

**Comment by jeffreyhanson** [comment] 2018-12-12 23:55
No worries - I'm just glad there wasn't a bug in prioritizr. I'd much prefer to have plenty of false reports then miss a true report :)

Yeah, the max features aims to meet as many targets as possible given the budget. If you wanted to lock in some targets, you could give them a higher weight with the `add_feature_weights` function.

Can  we close this issue then? I'll update the help file for `add_max_features_objective` to use a more reasonable budget.

**Comment by lizlaw** [comment] 2018-12-13 00:37
true that! 
yep, please do.

**Closed** 2018-12-13 01:18 UTC
Labels: question
