### ISSUE TITLE
Issues with add_connectivity_penalties() function

### ISSUE THREAD

**Issue by eleanorstewart17** [prioritizr/prioritizr#222] opened 2022-01-12 13:01 UTC
Hello,

I have no issues solving any basic problems, but when I try adding in the 'add_connectivity_penalties()' function I receive this error 'Error in stop(assertError(attr(res, "msg"))) : bad error message'. In the connectivity penalty function, I specify zones as NULL because I'm using a data.frame object as the argument to data. The dataframe contains the columns id1, id2 and boundary with 3,146,902 obs:
> head(influence_dataframe)
    id1 id2 boundary
1 14202   1 4.39e-06
2 14203   1 4.34e-06
3 14241   1 4.56e-06
4 14242   1 4.49e-06
5 14243   1 4.43e-06
6 14244   1 4.37e-06
 I've played around with various data formats, rescaling etc. and can't figure out where I'm going wrong. Any insight would be greatly appreciated!

See code below:

'library(scales)
library(tidyverse)
library(prioritizr)
library(gurobi)

# STEP 1: LOAD IN AND PROCESS DATA
### load pu data
pu_path <- 'Marxan/input/pu.dat'
pu_dat <- data.table::fread(pu_path, data.table = FALSE)

### load spec data
spec_path <- 'Marxan/input/spec.dat'
spec_dat <- data.table::fread(spec_path, data.table = FALSE)

### load puvspr data
puvspr_path <- 'Marxan/input/puvspr2.dat'
puvspr_dat <- data.table::fread(puvspr_path, data.table = FALSE)

### rescale feature amounts
x <-puvspr_dat[3]
x <- as.numeric(unlist(x))
head(x)

x_res <- rescale(x, to = c(0, 1))
puvspr_dat[3] <- x_res
puvspr_dat[3][puvspr_dat[3]<1e-6] <- 0

### load boundary file
bound_path <- 'Marxan/input/bound.dat'
bound_dat <- data.table::fread(bound_path, data.table = FALSE)

### load in current influence matrix connectivity penalty
influence_matrix_path <- 'connectivity_matrix_1.csv'
influence_df <- data.table::fread(influence_matrix_path, data.table=FALSE)

#### transform into correct format for add_connectivity_penalties()
influence_df <- as.data.frame(influence_df)
influence_df <- column_to_rownames(influence_df, 'ID')

values <- as.numeric(unlist(influence_df))

influence_dataframe <- data.frame(id1=rownames(influence_df)[row(influence_df)], 
                                  id2=colnames(influence_df)[col(influence_df)], 
                                  boundary=values)

influence_dataframe <- influence_dataframe[influence_dataframe$boundary !=0, ]

influence_dataframe$id1 <- as.numeric(influence_dataframe$id1)
influence_dataframe$id2 <- as.numeric(influence_dataframe$id2)
influence_dataframe$boundary <- as.numeric(influence_dataframe$boundary)

rownames(influence_dataframe) <- (1:3146902)

# STEP 2: RUN PROBLEMS
### 5. MARINE AND TERRESTRIAL WITH CURRENT INFLUENCE

targets <- c(0.1)
p5 <- problem(pu_dat, spec_dat, cost_column = "cost", 
              rij = puvspr_dat) %>%
  add_min_set_objective() %>%
  add_relative_targets(targets) %>%
  add_binary_decisions() %>%
  add_connectivity_penalties(penalty =2, zones =NULL, data=influence_dataframe) %>%
  add_gurobi_solver(threads=6)
'

Thanks a lot in advance!

**Comment by jeffreyhanson** [comment] 2022-01-15 21:13
Hi,

Thanks for reaching out! I'm currently on holiday with limited internet connectivity till the 24th Jan. @ricschuster, do you have any ideas? If not, I can follow up when I get back to work.

Briefly, it sounds like the format for the connectivity data is incorrect. The function has a bunch of checks to verify that the data format are correct, and these sometimes show the  "bad error" message (this should be considered a bug though, we ideally want these messages to be helpful). Could you try converting the connectivity data frame to matrix format (using `marxan_boundary_data_to_matrix`). I would guess this is the problem (prioritizr does this internally for data frame inputs). If this gives you the bad error message,  try going through each of the checks for this function individually to see which one is giving the bad error message (lines 55 - 108, https://github.com/prioritizr/prioritizr/blob/master/R/marxan_boundary_data_to_matrix.R).

**Comment by ricschuster** [comment] 2022-01-17 12:54
If Jeff's suggestion doesn't yield satisfactory results, you could send me your data and I could take a look if you'd like.

**Comment by eleanorstewart17** [comment] 2022-01-19 10:50
Hi both - thanks a lot for getting back to me. And no problem at all @jeffreyhanson  - enjoy your holiday! The marxan_boundary_data_to_matrix function doesn't give me the bad error message and the data frame passes all of the checks so I think it must be something else.

@ricschuster I will send you my data now - thanks a lot!

**Comment by jeffreyhanson** [comment] 2022-01-25 01:29
Thank you very much for sharing your data - that's really helpful! I was able to succesfully run the script in your repo on my computer, so I wonder if maybe one of the R packages on your computer needs updating?

I've pasted my session info below (obtained by running `sessionInfo()` after running the script), could you please compare this with your own session info to identify packages which might need updating (i.e. these will have a lower version number). Also, I'm using R version 4.1.2 - but I wouldn't have thought that would be needed?

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 21.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gurobi_9.5-0     slam_0.1-49      prioritizr_7.1.1 proto_1.0.0     
 [5] sf_1.0-5         raster_3.5-9     sp_1.4-6         forcats_0.5.1   
 [9] stringr_1.4.0    dplyr_1.0.7      purrr_0.3.4      readr_2.1.1     
[13] tidyr_1.1.4      tibble_3.1.6     ggplot2_3.3.5    tidyverse_1.3.1 
[17] scales_1.1.1     testthat_3.1.1   devtools_2.4.3   usethis_2.1.5   

loaded via a namespace (and not attached):
 [1] httr_1.4.2         pkgload_1.2.4      jsonlite_1.7.2     modelr_0.1.8      
 [5] assertthat_0.2.1   cellranger_1.1.0   remotes_2.4.2      sessioninfo_1.2.2 
 [9] pillar_1.6.4       backports_1.4.1    lattice_0.20-45    glue_1.6.0        
[13] uuid_1.0-3         rvest_1.0.2        colorspace_2.0-2   Matrix_1.4-0      
[17] pkgconfig_2.0.3    broom_0.7.10       haven_2.4.3        fasterize_1.0.3   
[21] processx_3.5.2     terra_1.4-22       tzdb_0.2.0         proxy_0.4-26      
[25] generics_0.1.1     ellipsis_0.3.2     cachem_1.0.6       withr_2.4.3       
[29] cli_3.1.0          magrittr_2.0.1     crayon_1.4.2       readxl_1.3.1      
[33] memoise_2.0.1      ps_1.6.0           fs_1.5.2           fansi_0.5.0       
[37] xml2_1.3.3         class_7.3-19       pkgbuild_1.3.0     data.table_1.14.2 
[41] tools_4.1.2        prettyunits_1.1.1  hms_1.1.1          lifecycle_1.0.1   
[45] munsell_0.5.0      reprex_2.0.1       callr_3.7.0        compiler_4.1.2    
[49] e1071_1.7-9        rlang_0.4.12       units_0.7-2        classInt_0.4-3    
[53] grid_4.1.2         rstudioapi_0.13    gtable_0.3.0       codetools_0.2-18  
[57] DBI_1.1.1          R6_2.5.1           lubridate_1.8.0    fastmap_1.1.0     
[61] utf8_1.2.2         rprojroot_2.0.2    KernSmooth_2.23-20 desc_1.4.0        
[65] stringi_1.7.6      parallel_4.1.2     Rcpp_1.0.7         vctrs_0.3.8       
[69] dbplyr_2.1.1       tidyselect_1.1.1  
```

**Comment by eleanorstewart17** [comment] 2022-01-25 11:39
Hi @jeffreyhanson - thanks very much for taking a look at it. That's very promising that the code ran on your machine! I did have packages that needed updated. I updated R, RStudio, prioritizr and gurobi and now have the same version or newer as all of your attached packages above but I'm still getting the bad error message. It's obviously something on my end so I'll keep digging! Here's my sessionInfo() below.

`sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gurobi_9.5-0     slam_0.1-50      prioritizr_7.1.1 proto_1.0.0      sf_1.0-5        
 [6] raster_3.5-15    sp_1.4-6         forcats_0.5.1    stringr_1.4.0    dplyr_1.0.7     
[11] purrr_0.3.4      readr_2.1.1      tidyr_1.1.4      tibble_3.1.6     ggplot2_3.3.5   
[16] tidyverse_1.3.1  scales_1.1.1    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8         lubridate_1.8.0    lattice_0.20-45    class_7.3-19      
 [5] assertthat_0.2.1   utf8_1.2.2         R6_2.5.1           cellranger_1.1.0  
 [9] backports_1.4.1    reprex_2.0.1       e1071_1.7-9        httr_1.4.2        
[13] pillar_1.6.4       rlang_0.4.12       uuid_1.0-3         readxl_1.3.1      
[17] rstudioapi_0.13    data.table_1.14.2  Matrix_1.3-4       munsell_0.5.0     
[21] proxy_0.4-26       broom_0.7.11       compiler_4.1.2     modelr_0.1.8      
[25] pkgconfig_2.0.3    tidyselect_1.1.1   codetools_0.2-18   fansi_1.0.2       
[29] crayon_1.4.2       tzdb_0.2.0         dbplyr_2.1.1       withr_2.4.3       
[33] grid_4.1.2         jsonlite_1.7.3     fasterize_1.0.3    gtable_0.3.0      
[37] lifecycle_1.0.1    DBI_1.1.2          magrittr_2.0.1     units_0.7-2       
[41] KernSmooth_2.23-20 cli_3.1.1          stringi_1.7.6      fs_1.5.2          
[45] xml2_1.3.3         ellipsis_0.3.2     generics_0.1.1     vctrs_0.3.8       
[49] tools_4.1.2        glue_1.6.1         hms_1.1.1          colorspace_2.0-2  
[53] terra_1.5-12       classInt_0.4-3     rvest_1.0.2        haven_2.4.3`

**Comment by ricschuster** [comment] 2022-01-25 12:56
Hi @jeffreyhanson 
Have you made any modifications to @eleanorstewart17's code to run things? 
If so, would you mind sharing the updated code?

I've tried this both on Linux and Windows and am getting `Error in stop(assertError(attr(res, "msg"))) : bad error message` on both.

**Comment by jeffreyhanson** [comment] 2022-01-25 22:24
Although I thought I was able to get the code working yesterday without any changes, I think I must have been mistaken. Today, I was able to reproduce the error that you're seeing. The issue is that setting `zones = NULL` is only needed to get `add_connectivity_penalties()` working with you have both (1) tabular connectivity data and (2) multiple zones. Since this problem only has a single zone, then `zones = NULL` throws an error. Sorry for not catching this earlier. I'll update the documentation to make it clearer when `zones = NULL` is actually needed. 

So, to get it working, I suggest using:

```
p5 <- problem(pu_dat, spec_dat, cost_column = "cost", rij = puvspr_dat) %>%
  add_min_set_objective() %>%
  add_relative_targets(targets) %>%
  add_binary_decisions() %>%
  add_connectivity_penalties(penalty = 2, data = influence_dataframe) %>%
  add_gurobi_solver(threads = 6)

```

@eleanorstewart17, does that work for you?

**Comment by ricschuster** [comment] 2022-01-25 22:29
Thanks very much @jeffreyhanson and sorry for not catching that `zones = NULL` issue either.
The code works for me now as well.

**Comment by eleanorstewart17** [comment] 2022-01-26 09:52
@jeffreyhanson it's working now, thanks so much! I had played around with including or not including `zones=NULL` and was still getting errors but that must have been before I formatted the influence dataframe correctly. Thank you both for your help!

**Comment by jeffreyhanson** [comment] 2022-01-26 20:58
Awesome - glad to hear its working now! Since we've resolved the issue, I'll close it now. Please feel free to re-open this issue or open a new one if you have any further questions.

**Closed by jeffreyhanson** 2022-01-26 20:58 UTC
Labels: question
