### ISSUE TITLE
Some type of infeasible problems

### ISSUE THREAD

**Issue by javierfajnolla** [prioritizr/prioritizr#84] opened 2018-05-11 21:10 UTC
Hi!

When using locked-out constraints, I have noticed that some prioritizr problems result infeasible after gurobi's pre-solve.
"Error in solve(problem_vert_pre) : conservation problem is infeasible"

The same prioritizr problem solves successfully when I do not use locked-out constraints or reduce the amount of locked-out planning units. This makes me think that the situation appears when some features occur completely in locked-out planning units, or at a sufficient extent over locked-out pixels as to make the achievement of their target imposible. 
Am I right? (sorry, I have not been able to test it well...).

Nonetheless, gurobi output gives me no clue that the situation is related to that ("Explored 0 nodes (0 simplex iterations)", or "Thread count was 1" (this is weird, I specified 2 as a parameter, and I know that 2 are successfully used when I do not use locked-out constraints), or "Solution count 0", or "Best objective -, best bound -, gap -")

However, if I am right about what causes the problem (feature targets become imposible when locking-out some planning units), I wanted to ask if there is any option to still solve the problem and report which features were problematic.

That would be Marxan's behavior. In my opinion, it is a very nice way to dealt with these situations, because you still can run the solution and learn which features will be compromised, given that the problem that you defined is correct (I mean, it can be a real world problem, that some targets are just imposible).

I am aware that I could calculate the maximum selectable area for each feature and compare that value with the target I am defining. Then, I could filter out those features that become infeasible. However, that kind of spoils the awesomeness of prioritizr that calculates targets and tables internally. I mean, those are operations that take a while when you have a large number of features, and prioritizr will calculate those things at some point anyway. However, I understand that this seems related to how gurobi works, and implementing a different behavior may require to do those calculations before sending data to gurobi, again repeating efforts... 
An option could be that the calculation is done when adding constraints or targets to a problem, and unfeasible species could be identified inside the object (somewhere like `problem$data[[5]]`). Later, gurobi will just get the instruction to get as much as possible from those species, and a warning would be produced indicating which species did not get as much as requested.

Is that possible to configure? If not, are there any thoughts about implementing something like this in future versions?

Anyway, thanks a lot for the great effort on this awesome package!
Javier

PD: Sorry, my files are too large as to provide them as example, but I am happy to help exploring if necessary!
Using prioritizr_4.0.0.11 and gurobi8 on a mac.

**Comment by jeffreyhanson** [comment] 2018-05-12 01:02
Hi,

Thanks for reaching out. I've tried to respond to each of your points/questions below (my responses in **bold**), but let me know if I've missed anything or my responses aren't clear. Since you talk about targets and infeasible problems, I will assume that your problem formulation uses the minimum set objective (but let me know if this isn't the case).

* When using locked-out constraints, I have noticed that some prioritizr problems result infeasible after gurobi's pre-solve. "Error in solve(problem_vert_pre) : conservation problem is infeasible"

  **Yeah, that error message means that there is no valid solution to the specified problem. For example, if you tried solving a minimum set problem with a target that required 321 occurrences of species A, and species A only occurred in 10 units, then there is no valid (or feasible) solution to this problem. Even selecting every single planning in the study area would not meet this target. I agree that this error message doesn't do a good job of explaining this.**

* The same prioritizr problem solves successfully when I do not use locked-out constraints or reduce the amount of locked-out planning units. This makes me think that the situation appears when some features occur completely in locked-out planning units, or at a sufficient extent over locked-out pixels as to make the achievement of their target impossible. Am I right? (sorry, I have not been able to test it well...).

  **Yeah, I think that's right.**

* Nonetheless, gurobi output gives me no clue that the situation is related to that ("Explored 0 nodes (0 simplex iterations)", or "Thread count was 1" (this is weird, I specified 2 as a parameter, and I know that 2 are successfully used when I do not use locked-out constraints), or "Solution count 0", or "Best objective -, best bound -, gap -")

  **Yeah, Gurobi (versions 7 and 8) only use a single thread during the presolve step, and will then use multiple threads after the presolve step (if specified).**

* However, if I am right about what causes the problem (feature targets become impossible when locking-out some planning units), I wanted to ask if there is any option to still solve the problem and report which features were problematic.

  **I would suggest trying the [`add_max_features_objective`](https://prioritizr.github.io/prioritizr/reference/add_max_features_objective.html) and with a really high budget. The minimum set objective is designed to find the solution with minimal cost that meets all the targets. The maximum features objective, on the other hand, is designed to find the solution that meets are many as targets as possible within the budget (and given multiple solutions that meet all the targets it returns the one with the smallest cost). So, if you have targets that cannot be met, then the maximum features objective will just simply not meet them. Though its worth noting problems with the maximum features objective can take much longer to solve than the set problem objective.**

* That would be Marxan's behavior. In my opinion, it is a very nice way to dealt with these situations, because you still can run the solution and learn which features will be compromised, given that the problem that you defined is correct (I mean, it can be a real world problem, that some targets are just impossible).

  **This might just be my personal preference, but I disagree with this. When I've tried solving problems where there is no feasible solution, I find it really helpful that _prioritizr_ tells me that there is no feasible solution and returns an error. This might be because I haven't formatted the input data correctly, or there was an error in my calculations for setting targets (e.g. if I per-calculate the targets using interpolation thresholds), or because I used a constraint that isn't appropriate (e.g. [`add_contiguity_constraints`](https://prioritizr.github.io/prioritizr/reference/add_contiguity_constraints.html) with some island planning units). I would not want _prioritizr_ to try (arbitrarily) removing some constraints and forcibly solving the problem, because the solution it would return would not be the solution to the problem I constructed. Does that make sense? What do you think?**

* I am aware that I could calculate the maximum selectable area for each feature and compare that value with the target I am defining. Then, I could filter out those features that become infeasible. However, that kind of spoils the awesomeness of prioritizr that calculates targets and tables internally. I mean, those are operations that take a while when you have a large number of features, and prioritizr will calculate those things at some point anyway. However, I understand that this seems related to how gurobi works, and implementing a different behavior may require to do those calculations before sending data to gurobi, again repeating efforts...

  **Another option might be to construct the problem, then generate a solution containing every planning unit, then use the [`feature_representation`](https://prioritizr.github.io/prioritizr/reference/feature_representation.html) function to calculate how well the features are represented in the solution, and then see if the targets are met? I agree it's not ideal, but it saves having to calculate planning unit by feature data. For example:**

  ```
  # load packages
  library(prioritizr)

  # build problem
  p <- problem(sim_pu_polygons, sim_features, "cost") %>%
       add_min_set_objective() %>%
       add_relative_targets(0.17) %>%
       add_binary_decisions()

  # generate fake solution
  s <- sim_pu_polygons
  s$solution <- 1

  # calculate representation
  r <- feature_representation(p, s[, "solution", drop = FALSE])
  ```

  An option could be that the calculation is done when adding constraints or targets to a problem, and unfeasible species could be identified inside the object (somewhere like problem$data[[5]]). Later, gurobi will just get the instruction to get as much as possible from those species, and a warning would be produced indicating which species did not get as much as requested.

  **Yeah, that could be possible for simple formulations (e.g. with locked out constraints). But it would be tricky to implement a general method that would identify the highest feasible possible target for problems with more complex constraints where the feasibility calculations don't just involve subsetting planning units (e.g. when using constraints like [`add_feature_contiguity_constraints`](https://prioritizr.github.io/prioritizr/reference/add_feature_contiguity_constraints.html) and [`add_neighbor_constraints`](https://prioritizr.github.io/prioritizr/reference/add_neighbor_constraints.html)). Maybe we could do try [relaxing constraints](https://www.gurobi.com/documentation/7.5/examples/diagnose_and_cope_with_inf.html), but this could be tricky too.**

* Is that possible to configure? If not, are there any thoughts about implementing something like this in future versions?

  **I think the general-case problem is that _prioritizr_ doesn't tell us which targets/constraints aren't feasible when it tries to solve a problem. It just says the problem isn't infeasible. _Gurobi_ can identify which targets/constraints in a problem aren't feasible (using [IISMethod](http://www.gurobi.com/documentation/8.0/refman/iismethod.html)), so I think it's technically possible to do this. Perhaps we could write a `check_feasibility` function that could be used to verify if a problem is feasible or not. If a problem isn't feasible, this function could also return information on which targets/constraints are infeasible? Do you think that would be useful? Although, it's not ideal because it would require _Gurobi_ because neither the _Rsymphony_ or _lpsymphony_ packages, and _prioritizr_ tries to avoid locking the user to a specific solver.**

**Comment by javierfajnolla** [comment] 2018-05-15 21:43
Hi and thanks for the time taken in reading and responding!

Such long responses give me quite many options to proceed easier to calculate everything myself, thanks a lot! 

For the moment, I will go for calculating maximum representation by generating a fake solution with all pu and then compare with the targets. That will allow me to write down which species are infeasible and decide whether to reduce just their target (for instance, to 0.95 of the maximum) or something else. You were right, I am using the minimum set objective approach (and I will keep my comments referring to that approach). 
I would add that it would be awesome to be able to recover from a defined problem object the actual targets that prioritizr will use. Not even in the most complicated case of using loglinear target this is difficult to calculate manually, but it wouldn't hurt to get it directly from the object (for instance, get a table from "problem$data$targets").

I agree with you that it does not make sense to give back a solution that is not for the exact problem that was given to prioritizr (e.g. using the maximum proportion for those features that are infeasible). 
But, considering the practical side of a conservation problem, I think this will be a common situation for real world problems. And you will need to find a solution if you want to give a response to this real world conservation problem. 
So, my guess is that most people will end up doing all the steps manually to adapt their problems to a feasible scenario. This is absolutely doable, but can take some time (e.g. for the case of needing to reduce infeasible species target to the maximum available: finding problematic species, changing approach to define targets manually instead of using the automated ones, maybe subsetting the raster stacks if you want to drop the species...).

So, while I agree with you, in the ideal scenario I would like prioritizr to help me in that process. I liked very much how does it sound the 'check_feasibility()' function that you mentioned (or 'make_feasible()'), and that function could be able to modify the problem by reducing targets to maximum values posible. Another option would be to add that option to 'solve()' (something like reduce_target_if_infeasible = TRUE), but I agree that the solve() function is beautiful simple as it is.

All that being said, again, I am so grateful for all the work you have done on the package. It is truly awesome!

Thanks again,
Javier

**Comment by jeffreyhanson** [comment] 2018-05-17 22:56
Yeah, I agree that manually identifying and changing infeasible targets could take some time, but hopefully if we added some functions like `check_feasibility` or `feature_abundances` (e.g.  to get the maximum amount of each feature in the planning units) then would make things easier. To make it easier for us to keep track of these feature proposals, I'll create a separate issue for each topic and link them here. 

I think I've addressed all your questions about using _prioritizr_ so I'll close this issue for now, but let me know if I've missed anything and feel free to reopen this issue if needed.

**Closed by jeffreyhanson** 2018-05-17 22:56 UTC
