### ISSUE TITLE
please change check in `add_manual_locked_constraints()`

### ISSUE THREAD

**Issue by tim-lenters** [prioritizr/prioritizr#288] opened 2023-06-23 13:31 UTC
Hi team,

I'm setting up a multizonal prioritization problem but have trouble adding locked out constraints. I use the `tibble` format specified in the tutorial with a column `pu`. Although the `pu` column corresponds to the correct row in the `cost` `data.frame` (I use the `data.frame` format and not e.g., `raster`), `add_manual_locked_constraints()` throws an error

The check `max(data$pu) <= number_of_total_units(x)` does not work as the `max(data$pu)` is larger than the numer of units. This is because `pu` is calculated before removing NA values. 

Would it be possible to change the check to: `length(unique(data$pu)) <= number_of_total_units(x)`? This should still achieve the same, but not break my code

Thanks!

**Comment by jeffreyhanson** [comment] 2023-06-23 16:56
Hi @tim-lenters,

Thank you very much for raising this issue! Hmm, I think the values in `data$pu` should correspond to row numbers in the planning unit data frame (in this case). It sounds like you subsetted planning unit data before using it with `problem()` (e.g. using `na.omit()`) and are then trying to use the un-subsetted version with `add_manual_locked_constraints()` - is that right? Sorry if I've misunderstood. If I have misunderstood, I've included a reprex below - could you please modify it to re-create the issue you're encountering? Although I could simply delete the check, I'm not sure if the check is a false positive or if it is correctly catching some invalid input that could lead to invalid results - and I'd like to verify that it's definitely the former before removing it. 

```
# import data
sim_pu_data <- get_sim_pu_polygons()
sim_pu_data <- sf::st_drop_geometry(sim_pu_data)[1:5, , drop = FALSE]
sim_pu_data$cost <- c(1, 10, 3, 4, 8)
sim_pu_data$spp_1 <- runif(5)
sim_pu_data$spp_2 <- runif(5)
sim_pu_data$spp_3 <- runif(5)

# create problem
p <-
  problem(sim_pu_data, c("spp_1", "spp_2", "spp_3"), cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_proportion_decisions() %>%
  add_manual_locked_constraints(
    data.frame(pu = c(1, 3, 4, 5), status = rep(0.3, 4))
  )
```

**Comment by jeffreyhanson** [comment] 2023-06-26 18:34
Ah I understand. So the issue is that the `id` column doesn't match up with the row numbers in the planning unit data used in `problem()`? If so, I would suggest maybe the matrix format with the locked out constraints to specify the constraints. This has the benefit that you can (1) acheive the same result as your example above and (2) you can use columns in the subsetted data frame as inputs for making the constraints (meaning you don't have to play around with multiple id or indexing columns). E.g., maybe you could do something like this:

```
# load packages
library(sf)
library(prioritizr)

# create example planning data
sim_pu_data <- get_sim_pu_polygons()
sim_pu_data <- sim_pu_data[seq_len(10), , drop = FALSE]

# convert to data frame format
sim_pu_data <- sf::st_drop_geometry(sim_pu_data)

# add in id column
sim_pu_data$id <- seq_len(10)

# add in columns indicating which planning units should be
# locked out from which zones
## these constraints mean that planning units 1--5 can't be
## allocated to zone 1 or zone 2, but can be allocated to zone 3
sim_pu_data$locked_zone1 <- c(rep(TRUE, 5), rep(FALSE, 5))
sim_pu_data$locked_zone2 <- c(rep(TRUE, 5), rep(FALSE, 5))
sim_pu_data$locked_zone3 <- c(rep(FALSE, 10))

# add in cost data
## simulate some integer values
sim_pu_data$cost1 <- abs(rpois(10, 10)) + 1
sim_pu_data$cost2 <- abs(rpois(10, 10)) + 1
sim_pu_data$cost3 <- abs(rpois(10, 10)) + 1
## convert some values to NA to replicate your situation
sim_pu_data$cost1[2:4] <- NA
sim_pu_data$cost2[2:4] <- NA
sim_pu_data$cost3[2:4] <- NA

# create rij data for 3 species in 3 zones
sim_pu_data$spp1_zone1 <- runif(10)
sim_pu_data$spp2_zone1 <- runif(10)
sim_pu_data$spp3_zone1 <- runif(10)
sim_pu_data$spp1_zone2 <- runif(10)
sim_pu_data$spp2_zone2 <- runif(10)
sim_pu_data$spp3_zone2 <- runif(10)
sim_pu_data$spp1_zone3 <- runif(10)
sim_pu_data$spp2_zone3 <- runif(10)
sim_pu_data$spp3_zone3 <- runif(10)

# remove planning units with NA costs
keep_idx <- 
  !is.na(sim_pu_data$cost1) &
  !is.na(sim_pu_data$cost2) &
  !is.na(sim_pu_data$cost3)
sim_pu_data <-  sim_pu_data[keep_idx, , drop = FALSE]

# create problem
## create zones
zone_names <- zones(
  c("spp1_zone1", "spp2_zone1", "spp3_zone1"),
  c("spp1_zone2", "spp2_zone2", "spp3_zone2"),
  c("spp1_zone3", "spp2_zone3", "spp3_zone3"),
  zone_names = c("zone1", "zone2", "zone3"),
  feature_names = c("spp1", "spp2", "spp3")
)

## create full problem
p <-
  problem(
    sim_pu_data, 
    zone_names, 
    cost_column = c("cost1", "cost2", "cost3")
  ) %>%
  add_min_set_objective() %>%
  add_relative_targets(matrix(0.1, ncol = 3, nrow = 3)) %>%
  add_locked_out_constraints(
    as.matrix(
      as.data.frame(
        sim_pu_data[, c("locked_zone1", "locked_zone2", "locked_zone3")]
      )
    )
  ) %>%
  add_binary_decisions()
```

Note that this has some limitations though: (1) since we're exlcuding some planning units with non-zero rij values, the relative targets will be calculated as percentages based on the total values in the planning units with non-NA cost valuees; and (2) this approach won't let you specify fractional values (i.e. values between zero and one, but not equal to zero and one) for the locked values (n.b. this only would only be relevant if you're using proportion type decisions; e.g., you want to ensure that a planning unit is allocated to a zone with a value of 0.3).

How does that sound?

**Comment by tim-lenters** [comment] 2023-06-27 08:48
This is roughly what I'm doing now and it works great! However, I also want to include the option for action-dependent `pu` value (e.g., restoration being `pu==1` and management only being `pu==0.5`, meaning that some actions you would need more `pu`s to reach your target). Would this still be possible using the way you propose?

**Comment by jeffreyhanson** [comment] 2023-07-03 02:10
Sorry, I feel like I'm missing something, I don't exactly understand the question. In general, I would recommend treating each action as a different zone, so you would have a "restoration zone" and a "management zone", and so the optimization process is then deciding which planning untis should be allocated to which zones (i.e. restore, management, or neither). 

So, for example, you could have the rij data such that allocating a planning unit to the restoration zone gives half the benefits of the management zone (e.g. see https://prioritizr.net/articles/management_zones_tutorial.html). You could then specify targets (using `add_manual_targets()`) so that the targets can be met by allocating planning units to either zone (using the list-column option, see https://prioritizr.net/articles/management_zones_tutorial.html#multiple-zones-with-complex-targets). E.g., something like this:

```
targets_dataframe2 <- tibble::tibble(
  feature = c("spp1", "spp2",
  zone = list(c("restore", "manage"), c("restore", "manage")), 
  sense = c(">=", ">="), 
  type = c("absolute", "absolute"), 
  target = c(20, 20) 
)
```

Does that help?

**Comment by jeffreyhanson** [comment] 2023-07-07 03:44
@tim-lenters - I just wanted to follow up and ask if you're still having issues getting prioritizr to work?

**Comment by jeffreyhanson** [comment] 2023-07-19 22:58
Sorry to bug you again @tim-lenters - I just wanted to check if you were able to get the code working? Happy to answer any more questions if that's helpful?

**Comment by tim-lenters** [comment] 2023-07-31 14:48
Hi @jeffreyhanson, sorry just returned from holiday! 

Ah I get it now, the way you propose should work and is similar how I have it solved now. I was under the impression it wasn't completely possible this way, but I must have misunderstood.

Thanks for helping!

**Comment by jeffreyhanson** [comment] 2023-07-31 19:58
No worrie! Hope you had a good break!

Excellent - glad to hear its working now! 

If you don't have any further questions for the moment, shall we close the issue?

**Comment by tim-lenters** [comment] 2023-07-31 21:55
We can close it, thanks!

**Closed** 2023-07-31 22:14 UTC
Labels: bug
