### ISSUE TITLE
Strange results when including asymmetric connectivity

### ISSUE THREAD

**Issue by eleanorstewart17** [prioritizr/prioritizr#232] opened 2022-03-09 15:15 UTC
Hello, me again - sorry!

I've been getting slightly strange results from my current analyses and wondering if I'm missing something. The issue only occurs when I run my scenarios with asymmetric connectivity. I'm running three different scenarios, the only difference between them being the data used in the `add_connectivity_penalties()` function. Despite the differing data inputs, in all three scenarios the selected planning units and output statistics are exactly the same(and the same as the base solution that doesn't include any connectivity) and do not change even at varying connectivity penalty values from 0.00001 to 10,000. In addition, the output of the `eval_connectivity_summary()` function is 0 every time which doesn't seem correct from visually looking at the selected planning units. This issue **only** occurs when I run a scenario with **asymmetric** connectivity. When I run them with symmetric connectivity I get differing outputs that change with the penalty values and varying output connectivity values, as expected. Am I missing something or is this an expected outcome of using symmetric connectivity due to the potential reduction in selection options for the algorithm?

I've added my current code and data to a new repo that I've invited you to @jeffreyhanson, in case this is helpful like last time. Again, thanks a lot in advance!

**Comment by jeffreyhanson** [comment] 2022-03-09 21:00
Hi,

Yeah - that doesn't sound right. I would expect prioritizr to return diffreent solutions when using asymettric connectivity with different penalty values. I'm sorry, I'm really swamped at the moment - so I probably will only be able to get to this sometime next week. In the meantime, I would suggest checking the values in the assymetric connectivity matrix, such as checking that there are some non-zero values, the values aren't too high (e.g. I would suggest ensuring all values <= 1000), and the non-zero values aren't too low (e.g. > 1e-3). Sorry I can't be of more help.

**Comment by jeffreyhanson** [comment] 2022-03-23 06:16
Just to follow up, @eleanorstewart17 and I have been working through this togeather, and we realized this issue is caused by two seperate issues. First, the `add_connectivity_penalties()` function was incorrectly treating the asymmetric connectivity data as symmetric data. This was caused by a bug that occurs when the asymmetric connectivity data is input as a `data.frame` format, and all of the connectivity data pertain to a single direction (i.e. all connectivity values are `id1 -> id2`, and don't include any `id2 -> id1`).  Second, the way that the `add_connectivity_penalties()` function handles asymmetric connectivity is different from Marxan, and this leads to different results. The combination of these two issues led to very strange results.

To address this, future versions of prioritizr will split the connectivity functionality into two seperate functions. The `add_connectivity_penalties()` function will only be used for symmetric connectivity, and the (soon to be implemented) `add_asym_connectivity_penalties()` function will be used for asymetric connectivity. The advantage here is that by letting users specify exactly what kind of connectivity data they have, this means that (i) prioritizr can correctly distinguish between asymmetric and symmetric connectivity (across all input data formats, including data.frame format), and (ii) prioritizr can retain it's current connectivity formulation (per `add_connectivity_penalties()`) and also provide Marxan's formulation of asymmetric connectivity (per `add_asym_connectivity_penalties()`). Although these changes will be merged into the main branch once they've been reviewed, they can be accessed from the `asym_con` branch in the meantime (see https://github.com/prioritizr/prioritizr/tree/asym_con).

I think that covers the main points - @eleanorstewart17 could you please chime in if I've missed any important details?

**Closed** 2022-03-30 19:39 UTC
Labels: bug, question
