### ISSUE TITLE
Annoying text about "Found more than one class "tbl_df" in cache"

### ISSUE THREAD

**Issue by davidcanarte** [prioritizr/prioritizr#157] opened 2020-08-03 23:50 UTC
Hello Jeffrey

I have found this issue as closed, but I am stuck trying to find a solution for the annoying text as below

"Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
Also defined by ‘memisc’"

I downloaded prioritizr but  "Found more than ... " text keeps popping up

I just upgraded in a Mac and Windows machine to the latest R studio (1.3.1056.dmg and 1.3.1056.exe) and since then in both machines, the text pops up making reference of package "memisc". I have drop and uploaded memisc several time and still the same problem. 

Could you please give me a hand?

David

**Comment by jeffreyhanson** [comment] 2020-08-04 02:06
Hi,

Thanks for letting us know about this! Could you please post a small reproducible example (e.g. using the built-in datasets) and your session information (i.e. output from the R command `sessionInfo()`) ? This would really help me track down this issue.

**Comment by davidcanarte** [comment] 2020-08-04 12:26
HI Jeff. Thanks! I tried to make a reproducible example with the built-in-datasets but the warning is not appearing. The warning makes reference to the package "memisc". Do you mind if I send you the folder with the files and R project? You may only need to change the path and run until line 335. The folder contains draft code and mock data that I am testing to soon work on the real data.

**Comment by davidcanarte** [comment] 2020-08-04 20:31
PS: I re-run the code from the beginning and the error appears after loading the csv file and deleting one column. So I can share with a very short reproducible example and with only one file to upload. Please let me know if this will help.

**Comment by jeffreyhanson** [comment] 2020-08-04 21:43
Ok - thanks for trying it with the built-in datasets. Yeah, could you please email me your R code and data? That would be really helpful.

**Comment by davidcanarte** [comment] 2020-08-04 22:42
Thanks! I sent the folder by email

**Comment by davidcanarte** [comment] 2020-08-04 22:44
Thank you Jeff

Here is the folder of the project compressed. Please change the path and the error should be appearing soon.


And the sessionInfo from my computer

R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets
[6] methods   base

other attached packages:
 [1] arsenal_3.5.0      xlsx_0.6.3
 [3] readxl_1.3.1       tractor.base_3.3.2
 [5] Hmisc_4.4-0        Formula_1.2-3
 [7] survival_3.2-3     memisc_0.99.25.6
 [9] MASS_7.3-51.6      lattice_0.20-41
[11] summarytools_0.9.6 forcats_0.5.0
[13] stringr_1.4.0      purrr_0.3.4
[15] tibble_3.0.3       tidyverse_1.3.0
[17] dplyr_1.0.1        tidyr_1.1.1
[19] plyr_1.8.6         ggplot2_3.3.2
[21] readr_1.3.1

loaded via a namespace (and not attached):
 [1] matrixStats_0.56.0  fs_1.5.0
 [3] lubridate_1.7.9     RColorBrewer_1.1-2
 [5] httr_1.4.2          repr_1.1.0
 [7] tools_3.6.2         backports_1.1.8
 [9] R6_2.4.1            rpart_4.1-15
[11] DBI_1.1.0           colorspace_1.4-1
[13] nnet_7.3-14         withr_2.2.0
[15] tidyselect_1.1.0    gridExtra_2.3
[17] compiler_3.6.2      cli_2.0.2
[19] reportr_1.3.0       rvest_0.3.6
[21] htmlTable_2.0.1     xml2_1.3.2
[23] scales_1.1.1        checkmate_2.0.0
[25] digest_0.6.25       foreign_0.8-72
[27] base64enc_0.1-3     jpeg_0.1-8.1
[29] RNifti_1.1.0        pkgconfig_2.0.3
[31] htmltools_0.5.0     highr_0.8
[33] dbplyr_1.4.4        htmlwidgets_1.5.1
[35] rlang_0.4.7         rstudioapi_0.11
[37] pryr_0.1.4          generics_0.0.2
[39] jsonlite_1.7.0      acepack_1.4.1
[41] magrittr_1.5        rapportools_1.0
[43] Matrix_1.2-18       Rcpp_1.0.5
[45] munsell_0.5.0       fansi_0.4.1
[47] lifecycle_0.2.0     stringi_1.4.6
[49] grid_3.6.2          blob_1.2.1
[51] crayon_1.3.4        haven_2.3.1
[53] splines_3.6.2       xlsxjars_0.6.1
[55] pander_0.6.3        hms_0.5.3
[57] magick_2.4.0        knitr_1.29
[59] pillar_1.4.6        tcltk_3.6.2
[61] codetools_0.2-16    reprex_0.3.0
[63] glue_1.4.1          latticeExtra_0.6-29
[65] data.table_1.12.8   modelr_0.1.8
[67] png_0.1-7           vctrs_0.3.2
[69] ore_1.6.3           cellranger_1.1.0
[71] gtable_0.3.0        assertthat_0.2.1
[73] xfun_0.16           broom_0.7.0
[75] rJava_0.9-13        tinytex_0.25
[77] cluster_2.1.0       ellipsis_0.3.1



David Cañarte
Ph.D. Candidate
Department of Sociology
and Criminology
University of Florida
dcanarte@ufl.edu<mailto:dcanarte@ufl.edu>

On Aug 4, 2020, at 5:43 PM, Jeff Hanson <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]


Ok - thanks for trying it with the built-in datasets. Yeah, could you please email me your R code and data? That would be really helpful.

**Comment by jeffreyhanson** [comment] 2020-08-05 21:54
Sorry, I can't seem to find the attachment in the email. I think GitHub might have removed the attachment? Could you please send it to me directly at: jeffrey.hanson@uqconnect.edu.au?

**Comment by davidcanarte** [comment] 2020-08-11 12:22
Hi... I was wondering if you were able to fix the bug?

**Comment by jeffreyhanson** [comment] 2020-08-11 21:28
Hi, sorry for the slow progress on this. I'll try and give you an update later today. In the mean time, I think you can keep using prioritizr and ignore the extra/annoying printed text. It's not throwing an error is it? Last time we encountered this bug it wasn't causing any incorrect calculations or anything.

**Comment by jeffreyhanson** [comment] 2020-08-11 22:57
I'm just looking through your script now and I couldn't find where you're using the prioritizr R package? Just to check, are you using prioritizr?

**Comment by jeffreyhanson** [comment] 2020-08-11 23:07
I think I've reproduced the issue, could you please confirm if this code prints out the annoying cache text on your computer?

```
# load packages
library(tibble)
library(memisc)

# create data
d <- tibble(value = seq(0, 100))

# subset data
subset_d <- subset(d, d$value < 50)
# Found more than one class "tbl_df" in cache; using the first, from namespace  'tibble'
# Also defined by ‘memisc’
# Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
# Also defined by ‘memisc’
```

**Comment by davidcanarte** [comment] 2020-08-11 23:20
Hello

In a new R script I reproduced the following:

# load packages
library(tibble)
library(memisc)

# create data
d <- tibble(value = seq(0, 100))

# subset data
subset_d <- subset(d, d$value < 50)

And I still got the error.

"Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
Also defined by ‘memisc’
Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
Also defined by ‘memisc’
Found more than one class "tbl_df" in cache; using the first, from namespace ‘tibble’"


I’ve not tried prioritizer yet.

Thank you very much for taking care of this


David Cañarte
Ph.D. Candidate
Department of Sociology
and Criminology
University of Florida
dcanarte@ufl.edu<mailto:dcanarte@ufl.edu>

On Aug 11, 2020, at 7:07 PM, Jeff Hanson <notifications@github.com<mailto:notifications@github.com>> wrote:


# load packages
library(tibble)
library(memisc)

# create data
d <- tibble(value = seq(0, 100))

# subset data
subset_d <- subset(d, d$value < 50)

**Comment by jeffreyhanson** [comment] 2020-08-11 23:29
Ok great. I think this issue is being caused by the memisc R package and not the prioritizr R package. To clarify, this isn't an error message (error messages start with the prefix `Error:`), it's just text that is being printed out when the code is running (e.g. after running the code you can see that the `subset_d` object exists). The prioritizr R package previously had a similar issue due to the way it interfaced with the tibble R package, and it looks like the memisc R package also has this issue due to the way it currently faces with the tibble R package. To address this, I'll post an issue on the memisc R package GitHub repository with this example, and submit a pull request that should fix this issue in the memisc R package (since the same fix we used in prioritizr should work for memisc). I'll tag you in the post to keep you in the loop. How does that sound?

**Comment by jeffreyhanson** [comment] 2020-08-12 00:07
I've just posted an [issue on the memisc GitHub repository outlining the issue](https://github.com/melff/memisc/issues) and [submitted a PR to fix the issue with the memisc R package](https://github.com/melff/memisc/issues/47). Since this issue doesn't seem to be related to the prioritizr R package (but please correct me if I am wrong), I'll close this issue here and we can continue this discussion on the [memisc GitHub repository](https://github.com/melff/memisc/issues)? Is that OK?

**Comment by davidcanarte** [comment] 2020-08-12 00:20
Sounds great! I’ll wait for the answer from the medics:: developers. I appreciate very much for the help and time. Cheers :)


David Cañarte
Ph.D. Candidate
Department of Sociology
and Criminology
University of Florida
dcanarte@ufl.edu<mailto:dcanarte@ufl.edu>

On Aug 11, 2020, at 7:30 PM, Jeff Hanson <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]


Ok great. I think this issue is being caused by the memisc R package and not the prioritizr R package. To clarify, this isn't an error message (error messages start with the prefix Error:), it's just text that is being printed out when the code is running (e.g. after running the code you can see that the subset_d object exists). The prioritizr R package previously had a similar issue due to the way it interfaced with the tibble R package, and it looks like the memisc R package also has this issue due to the way it currently faces with the tibble R package. To address this, I'll post an issue on the memisc R package GitHub repository with this example, and submit a pull request that should fix this issue in the memisc R package (since the same fix we used in prioritizr should work for memisc). I'll tag you in the post to keep you in the loop. How does that sound?

**Comment by jeffreyhanson** [comment] 2020-08-12 20:01
No worries - I'm happy to help!

**Closed by jeffreyhanson** 2020-08-12 20:01 UTC
Labels: bug
