### ISSUE TITLE
bad error message

### ISSUE THREAD

**Issue by faengl** [prioritizr/prioritizr#104] opened 2018-12-28 14:48 UTC
I am trying to define a conservation problem for a large 34,667 x 25,666 raster-based set of 34,007,669 planning units (and 855,755,553 null-values) with 18 layers of features. As soon as I  run
`p <- problem(sim_pu, sim_feat)` I instantly get the following error message:
`Error in stop(assertError(attr(res, "msg"))) : bad error message`

This happens with or without specifying any targets, constrains or optimizer. Also reducing the features to two layers doesn't help.
When I crop a small area out of the original data the problem can be defined without any errors.

The server I am working on has about 160 GB of ram and 26 cores.
Do you think the error is related to the size of the input data?

Here is part of my session info:

R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RPostgreSQL_0.6-2 DBI_1.0.0         gurobi_8.1-0      slam_0.1-43      
[5] prioritizr_4.0.2  proto_1.0.0       raster_2.5-8      rgdal_1.3-6      
[9] sp_1.2-7         

loaded via a namespace (and not attached):
[1] compiler_3.4.4   assertthat_0.2.0 magrittr_1.5     Matrix_1.2-14   
[5] tools_3.4.4      Rcpp_0.12.16     grid_3.4.4       lattice_0.20-35

**Comment by ricschuster** [comment] 2018-12-29 15:44
Thanks for posting this issue @faengl 
Would you mind posting a reproducible code snippet, so we can investigate this problem further?

The problem could be too big as a raster. In this case you could use a `rij` matrix, as explained here: https://prioritizr.net/reference/problem.html

Example code:
```
# load data
data(sim_pu_raster, sim_pu_polygons, sim_pu_lines, sim_pu_points,
     sim_features)

# alternatively one can supply pre-processed aspatial data
costs <- sim_pu_polygons$cost
features <- data.frame(id = seq_len(nlayers(sim_features)),
                       name = names(sim_features))
rij_mat <- rij_matrix(sim_pu_polygons, sim_features)
p6 <- problem(costs, features, rij_matrix = rij_mat) %>%
      add_min_set_objective() %>%
      add_relative_targets(0.2) %>%
      add_binary_decisions()

s6 <- solve(p6)
```

**Comment by ricschuster** [comment] 2019-01-09 22:14
Hi @faengl,

Here a toy example of how I use this approach for bigger datasets. I will try the 25x25m data tonight, but for now here a working code snippet (including `add_boundary_penalty`):

```
library(raster)
library(prioritizr)
library(tidyverse)


pu.rast <- sim_pu_raster
bound_mat <- boundary_matrix(pu.rast)

feat <- sim_features
feat.nm <- names(feat)
spp <- 1

pu <- data.frame(id=seq(1:length(pu.rast)),cost=pu.rast[],status=0)
rij.id <- data.frame(pu=pu$id)

rij <- data.frame(pu=vector(),species=vector(),amount=vector())
for (jj in 1:nlayers(feat)){
  
  print(feat.nm[jj])
  flush.console()
  
  rij.tmp <- data.frame(pu=rij.id$pu,species=spp,amount=feat[[jj]][])
  
  spp <- spp + 1
  
  rij.tmp <- drop_na(rij.tmp)
  rij <- rbind(rij,rij.tmp)
  rm(rij.tmp)
  gc()
}


features <- data.frame(id=seq(1,spp-1),name=feat.nm, stringsAsFactors = F)

p1 <- problem(pu, features, rij, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_binary_decisions() 

s1 <- solve(p1 %>% add_relative_targets(0.30))

out.r <- pu.rast
out.r[] <- ss$solution_1

# create a problem using precomputed boundary data
p2 <- p1 %>% add_boundary_penalties(50, 1, data = bound_mat)

s2 <- solve(p2 %>% add_relative_targets(0.30))

out.r2 <- pu.rast
out.r2[] <- s2$solution_1


plot(stack(out.r, out.r2))
```

**Comment by faengl** [comment] 2019-01-10 08:30
Hi @ricschuster ,

I will try that as soon as possible. Thanks!
Also I noted some general issues with my data: The features area distributed area-wide. I should reduce them to forests using a forest mask.
Secondly I am working on an approach that reduces resolution to 1 ha (100x100m).

**Comment by ricschuster** [comment] 2019-01-10 15:34
You are welcome. I tried the above method with the 25x25m dataset overnight and it blew up my RAM. 50x50m is processing now and the rij file is working. When trying to solve the problem I do get an error though, which likely has to do with how your data is setup:

`Error in solve(p1 %>% add_relative_targets(0.3)) : 
  conservation problem is infeasible`

**Comment by faengl** [comment] 2019-01-11 16:09
Hi @ricschuster ,

that's really cool! I just ran your code example with my (newly created and hopefully improved) 100x100 data. The first problem without boundary data runs perfectly within some minutes on my regular machine. I didn't have the time to run `p2` yet but I will as soon as possible.
I guess I must apologize for my data. As I said I noticed some flaws about it: The first problem is that there is a "full coverage" of all features. If you look at all features called feat_grl_* you will notice that they cover the entire area of Germany. They should cover only the forested area. So I masked out the forests. Now there are a lot more NULL-cells in the data. Not sure if that is relevant for performance. At least there is a mayor effect when specifying relative targets since with "full coverage" a fraction of the entire land area will be the target value and with forests masked out a fraction of the forested area will be the target value.
Also there is another problem: In my original data I tried to aggregate pixels with a resolution of 25x25 m. This approach is probably more a classification or object aggregation thing as practiced in remote sensing. No I use a coarser resolution (100x100) which is more a actual "planning unit" approach.
Please let me know if you want my latest data for testing. But with your code I can work on from now I think... Thanks again!

**Comment by ricschuster** [comment] 2019-01-12 04:14
Great to hear that its working and no need to apologize. Always happy to help as I can. 

As for masking targets, the important part is the pu raster. You can remove elements with `NA` values from both the pu `data.frame` as well as the rij matrix, with something like this (not tested just from memory, so might need some adjustment:

```
pu.red <- pu[!is.na(pu$cost),]
 rij.red <- rij[rij$pu %in% pu.red$id, ]
```

As for resolution, I'm not sure I understand the problem with that. Are you wondering about the best way to aggregate from 25x25m to 100x100m? 
I usually use [gdalwarp](https://www.gdal.org/gdalwarp.html) and call it some like this:

```
system(paste("gdalwarp -r average",
            PATH_TO_SOURCE_FILE,
            PATH_TO_DESTINATION_FILE,sep=" "))
```
The source file would be your 25x25m raster, the destination your 100x100m raster, which needs to exist already. I usually create a blank raster with the correct resolution and extent.
Depending on your data you might want to use something other than average.

**Comment by faengl** [comment] 2019-01-19 15:51
Hi, thanks for the null omitting approach. Actually I didn't use it yet because my 100x100 problem can be solved as it is, incluing the `add_boundary_penalties`. But I am sure it will improve the performance. I will give it a try. Also I'm glad that you showed me how to convert between raster, data frame and, most important, back to raster. I was always wondering how the cell ids of a raster can be preserved when storing cell values in a data frame for later use to write back data to raster cells.
For changing the resolution of my data I have been using gdalwarp, too. My thoughts about the resolution were more philosophical: I meant that when using a software like prioritizr one would probably assume that the planning units are more ore less representing units in the real world that are manageable. Such units would probably have a size in the order of hectares. What I wanted to do initially was to aggregate pixel with a much finer resolution (25x25). Those pixels are not real planning units but rather pixel of an image like in remote sensing. I was just wondering if you thought of this kind of usage too, when developing prioritizr.

My initial question was about an undefined error message when using large raster files. So there is some kind of size threshold above which prioritizr (ore one of the components) will aboard immediately when execution the `problem` function? If so, I think it would be a good idea to issue a corresponding error message. Or do you think the error is not reproducible and maybe depends on my hard and software?

**Comment by ricschuster** [comment] 2019-01-22 14:18
You are welcome.

As for resolution, good point and this is an important issue I have been thinking about a lot, ever since I started using prioritization approaches. There is no good answer to this question really (I think). On top of the resolution question, we also need to ask the planning unit shape question. What planning unit shape makes the most sense? In your case its probably most efficient to use raster cells, but in other cases one could argue for polygons, such as watersheds, properties, ...
For my PhD I used mostly property boundaries, which then leads to the question of how to best aggregate feature data to the planning unit scale. No best solution for that question either in my opinion, but some fascinating discussions to be had when thinking about this kind of stuff.

As for the error message @jeffreyhanson would be the best person to answer that question.

**Comment by jeffreyhanson** [comment] 2019-01-22 22:55
Sorry, I'm only getting to this thread now. The `problem` function (and most of the functions in prioritzr) has a series of checks that it runs to verify that the input arguments/data conform to certain expectations (using the assertthat R Package). It looks like the input arguments/data aren't passing these checks, but the asserthat R package is having trouble parsing a helpful error message and so it's outputting `"bad error message"` instead (this can sometimes happen for complicated checks). So, I don't think this issue is specifically due to the data being too large, though once we work what validity check is failing, it might turn that the data is too large anyway.

@faengl, could you please send me a copy of the data and I'll see what I can do? I'll see if I can work out what check is failing, and I'll update prioritizr so that it outputs a helpful message in the future.

**Comment by faengl** [comment] 2019-01-30 15:22
Hi @jeffreyhanson, can you give me an email address so I can sent you a link to the data? I can't post it here on github.

**Comment by jeffreyhanson** [comment] 2019-01-30 23:21
Sure - please email me at jeffrey.hanson@uqconnect.edu.au - thank you.

**Comment by jeffreyhanson** [comment] 2019-02-03 10:50
Ok, I've just pushed a patch to fix the `bad error message` bug. For reference, the issue was that the data verification checks were failing because the cost data and the feature data have different spatial properties (i.e. they need the same resolution, extent, coordinate reference system, resolution, and number of rows + columns, see `raster::compareRaster` for more info), and the code used to display a helpful error message (i.e. `assertthat::assert_that`) was failing for this particular verification check. 

@faengl, thanks so much for reporting this bug and your help with tracking it down. Did you have any further questions? If not, I'll close this issue.

**Comment by faengl** [comment] 2019-02-03 15:36
I will try `raster::compareRaster`, didn't know about it. That's probably a very helpful tool.
If you want to close the thread, please go ahead. Thank's for fixing the error messages!

**Comment by jeffreyhanson** [comment] 2019-02-03 22:54
Yeah - I find that function very useful. I had a quick look and the feature and planning unit rasters had different `xmin` values for their extents. Also, just in case you haven't heard of it, `raster::compareCRS`  can be very helpful too. 

Ok - will do - thanks again for reporting this bug.

**Closed by jeffreyhanson** 2019-02-03 22:54 UTC
Labels: bug
